version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: OrchidUserService
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - orchid_network

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://root:root@db:5432/OrchidUserService?sslmode=disable
    depends_on:
      - db
    entrypoint: ["/app/backend", "conf/conf_development.yml"] 
    networks:
      - orchid_network

volumes:
  postgres_data:
    driver: local

networks:
  orchid_network:
    driver: bridge
