version: '3.8'

services:
  userservice:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgres://UserService:User@Service@postgres:5432/OrchidUserService?sslmode=disable"
    depends_on:
      - postgres 

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: UserService
      POSTGRES_PASSWORD: User@Service
      POSTGRES_DB: OrchidUserService
    ports:
      - "5433:5432"

