-- Create Orders Table
BEGIN;

CREATE TABLE "Orders" (
  "OrderID" SERIAL PRIMARY KEY,
  "CustomerOrderId" INT, -- if needed; can be generated by client or a sequence
  "UserId" INT NOT NULL,
  "PhoneNumber" VARCHAR(100) NOT NULL,
  "OrderItems" JSONB NOT NULL, 
  "CreatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("UserId") REFERENCES "User" ("ID") ON DELETE CASCADE
) TABLESPACE pg_default;

COMMIT;
