BEGIN;

CREATE TABLE "adminPermission" (
    "PermissionID" SERIAL PRIMARY KEY,
    "AdminID" INT REFERENCES "User" ("ID") ON DELETE CASCADE,
    "CanCreate" BOOLEAN DEFAULT FALSE,
    "CanRead" BOOLEAN DEFAULT TRUE,
    "CanUpdate" BOOLEAN DEFAULT FALSE,
    "CanDelete" BOOLEAN DEFAULT FALSE,
    "AssignedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "FK_ADMINID" FOREIGN KEY ("AdminID") REFERENCES "User" ("ID")
) TABLESPACE pg_default;

COMMIT;