--TABLE: "images"
BEGIN;

CREATE TABLE "imagesMn" (
    "Id" SERIAL PRIMARY KEY,
    "ProductMnID" INT NOT NULL,
    "ImagePath" TEXT NOT NULL,
    "Created_At" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "FK_Product_ID" FOREIGN KEY ("ProductMnID") REFERENCES "productMn" ("ProductMnID") ON DELETE CASCADE
) TABLESPACE pg_default;

COMMIT;