-- TABLE "payments"
BEGIN;

CREATE TABLE "payments" (
    "PaymentID" SERIAL PRIMARY KEY,
    "OrderID" INT NOT NULL,
    "UserID" INT NOT NULL,
    "PaymentMethod" VARCHAR(50) NOT NULL,
    "PaymentStatus" VARCHAR(50) NOT NULL,
    "Amount" DECIMAL(10, 2) NOT NULL,
    "Created_At" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "Updated_At" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "FK_Payment_OrderID" FOREIGN KEY ("OrderID") REFERENCES "OrderItems" ("OrderItemId") ON DELETE CASCADE,
    CONSTRAINT "FK_Payment_UserID" FOREIGN KEY ("UserID") REFERENCES "User" ("ID") ON DELETE CASCADE
) TABLESPACE pg_default;

COMMIT;