// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type User struct {
	ID               int32
	LastName         string
	FirstName        string
	UserName         string
	Email            string
	IsHashedPassword string
	IsAdmin          bool
	IsUser           bool
	IsSuperAdmin     bool
	IsActive         bool
	CreatedAt        time.Time
}
