// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: productMn.sql

package db

import (
	"context"
	"database/sql"
)

const createProductMn = `-- name: CreateProductMn :one
INSERT INTO
    "productMn" (
        "ProductNameMn",
        "sCategoryIdMn",
        "PriceMn",
        "StockQuantity",
        "ImagesPathMn",
        "DescriptionMn",
        "BrandMn",
        "ManufacturedCountryMn",
        "ColorId",
        "SizeId",
        "PenOutputMn",
        "FeaturesMn",
        "MaterialMn",
        "StapleSizeMn",
        "CapacityMn",
        "WeightMn",
        "ThicknessMn",
        "PackagingMn",
        "ProductCodeMn",
        "CostPriceMn",
        "RetailPriceMn",
        "WarehouseStockMn"
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17,
        $18,
        $19,
        $20,
        $21,
        $22
    ) RETURNING "ProductMnID", "ProductNameMn", "sCategoryIdMn", "PriceMn", "StockQuantity", "ImagesPathMn", "DescriptionMn", "BrandMn", "ManufacturedCountryMn", "ColorId", "SizeId", "PenOutputMn", "FeaturesMn", "MaterialMn", "StapleSizeMn", "CapacityMn", "WeightMn", "ThicknessMn", "PackagingMn", "UsageMn", "InstructionsMn", "ProductCodeMn", "CostPriceMn", "RetailPriceMn", "WarehouseStockMn", "Created_At", "Updated_At"
`

type CreateProductMnParams struct {
	ProductNameMn         string
	SCategoryIdMn         int32
	PriceMn               string
	StockQuantity         int32
	ImagesPathMn          string
	DescriptionMn         string
	BrandMn               string
	ManufacturedCountryMn string
	ColorId               int32
	SizeId                int32
	PenOutputMn           string
	FeaturesMn            string
	MaterialMn            string
	StapleSizeMn          string
	CapacityMn            string
	WeightMn              string
	ThicknessMn           string
	PackagingMn           string
	ProductCodeMn         string
	CostPriceMn           string
	RetailPriceMn         string
	WarehouseStockMn      int32
}

func (q *Queries) CreateProductMn(ctx context.Context, arg CreateProductMnParams) (ProductMn, error) {
	row := q.db.QueryRowContext(ctx, createProductMn,
		arg.ProductNameMn,
		arg.SCategoryIdMn,
		arg.PriceMn,
		arg.StockQuantity,
		arg.ImagesPathMn,
		arg.DescriptionMn,
		arg.BrandMn,
		arg.ManufacturedCountryMn,
		arg.ColorId,
		arg.SizeId,
		arg.PenOutputMn,
		arg.FeaturesMn,
		arg.MaterialMn,
		arg.StapleSizeMn,
		arg.CapacityMn,
		arg.WeightMn,
		arg.ThicknessMn,
		arg.PackagingMn,
		arg.ProductCodeMn,
		arg.CostPriceMn,
		arg.RetailPriceMn,
		arg.WarehouseStockMn,
	)
	var i ProductMn
	err := row.Scan(
		&i.ProductMnID,
		&i.ProductNameMn,
		&i.SCategoryIdMn,
		&i.PriceMn,
		&i.StockQuantity,
		&i.ImagesPathMn,
		&i.DescriptionMn,
		&i.BrandMn,
		&i.ManufacturedCountryMn,
		&i.ColorId,
		&i.SizeId,
		&i.PenOutputMn,
		&i.FeaturesMn,
		&i.MaterialMn,
		&i.StapleSizeMn,
		&i.CapacityMn,
		&i.WeightMn,
		&i.ThicknessMn,
		&i.PackagingMn,
		&i.UsageMn,
		&i.InstructionsMn,
		&i.ProductCodeMn,
		&i.CostPriceMn,
		&i.RetailPriceMn,
		&i.WarehouseStockMn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deductSockQuantityByProductMnID = `-- name: DeductSockQuantityByProductMnID :one
UPDATE
    "productMn"
SET
    "StockQuantity" = "StockQuantity" - $1
WHERE
    "ProductMnID" = $2
    AND "StockQuantity" >= $1 RETURNING "ProductMnID", "ProductNameMn", "sCategoryIdMn", "PriceMn", "StockQuantity", "ImagesPathMn", "DescriptionMn", "BrandMn", "ManufacturedCountryMn", "ColorId", "SizeId", "PenOutputMn", "FeaturesMn", "MaterialMn", "StapleSizeMn", "CapacityMn", "WeightMn", "ThicknessMn", "PackagingMn", "UsageMn", "InstructionsMn", "ProductCodeMn", "CostPriceMn", "RetailPriceMn", "WarehouseStockMn", "Created_At", "Updated_At"
`

type DeductSockQuantityByProductMnIDParams struct {
	QuantityPurchased int32
	ProductMnID       int32
}

func (q *Queries) DeductSockQuantityByProductMnID(ctx context.Context, arg DeductSockQuantityByProductMnIDParams) (ProductMn, error) {
	row := q.db.QueryRowContext(ctx, deductSockQuantityByProductMnID, arg.QuantityPurchased, arg.ProductMnID)
	var i ProductMn
	err := row.Scan(
		&i.ProductMnID,
		&i.ProductNameMn,
		&i.SCategoryIdMn,
		&i.PriceMn,
		&i.StockQuantity,
		&i.ImagesPathMn,
		&i.DescriptionMn,
		&i.BrandMn,
		&i.ManufacturedCountryMn,
		&i.ColorId,
		&i.SizeId,
		&i.PenOutputMn,
		&i.FeaturesMn,
		&i.MaterialMn,
		&i.StapleSizeMn,
		&i.CapacityMn,
		&i.WeightMn,
		&i.ThicknessMn,
		&i.PackagingMn,
		&i.UsageMn,
		&i.InstructionsMn,
		&i.ProductCodeMn,
		&i.CostPriceMn,
		&i.RetailPriceMn,
		&i.WarehouseStockMn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteByProductMnId = `-- name: DeleteByProductMnId :exec
DELETE FROM
    "productMn"
WHERE
    "ProductMnID" = $1
`

func (q *Queries) DeleteByProductMnId(ctx context.Context, productmnid int32) error {
	_, err := q.db.ExecContext(ctx, deleteByProductMnId, productmnid)
	return err
}

const filterByProductMnName = `-- name: FilterByProductMnName :many
SELECT
    "ProductMnID", "ProductNameMn", "sCategoryIdMn", "PriceMn", "StockQuantity", "ImagesPathMn", "DescriptionMn", "BrandMn", "ManufacturedCountryMn", "ColorId", "SizeId", "PenOutputMn", "FeaturesMn", "MaterialMn", "StapleSizeMn", "CapacityMn", "WeightMn", "ThicknessMn", "PackagingMn", "UsageMn", "InstructionsMn", "ProductCodeMn", "CostPriceMn", "RetailPriceMn", "WarehouseStockMn", "Created_At", "Updated_At"
FROM
    "productMn"
WHERE
    "ProductNameMn" ILIKE '%' || $1 || '%' -- Case-insensitive search for partial match
ORDER BY
    "Created_At" DESC
`

func (q *Queries) FilterByProductMnName(ctx context.Context, productnamemn sql.NullString) ([]ProductMn, error) {
	rows, err := q.db.QueryContext(ctx, filterByProductMnName, productnamemn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductMn
	for rows.Next() {
		var i ProductMn
		if err := rows.Scan(
			&i.ProductMnID,
			&i.ProductNameMn,
			&i.SCategoryIdMn,
			&i.PriceMn,
			&i.StockQuantity,
			&i.ImagesPathMn,
			&i.DescriptionMn,
			&i.BrandMn,
			&i.ManufacturedCountryMn,
			&i.ColorId,
			&i.SizeId,
			&i.PenOutputMn,
			&i.FeaturesMn,
			&i.MaterialMn,
			&i.StapleSizeMn,
			&i.CapacityMn,
			&i.WeightMn,
			&i.ThicknessMn,
			&i.PackagingMn,
			&i.UsageMn,
			&i.InstructionsMn,
			&i.ProductCodeMn,
			&i.CostPriceMn,
			&i.RetailPriceMn,
			&i.WarehouseStockMn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findByProductIdMn = `-- name: FindByProductIdMn :one
SELECT
    "ProductMnID", "ProductNameMn", "sCategoryIdMn", "PriceMn", "StockQuantity", "ImagesPathMn", "DescriptionMn", "BrandMn", "ManufacturedCountryMn", "ColorId", "SizeId", "PenOutputMn", "FeaturesMn", "MaterialMn", "StapleSizeMn", "CapacityMn", "WeightMn", "ThicknessMn", "PackagingMn", "UsageMn", "InstructionsMn", "ProductCodeMn", "CostPriceMn", "RetailPriceMn", "WarehouseStockMn", "Created_At", "Updated_At"
FROM
    "productMn"
WHERE
    "ProductMnID" = $1
LIMIT
    1
`

func (q *Queries) FindByProductIdMn(ctx context.Context, productmnid int32) (ProductMn, error) {
	row := q.db.QueryRowContext(ctx, findByProductIdMn, productmnid)
	var i ProductMn
	err := row.Scan(
		&i.ProductMnID,
		&i.ProductNameMn,
		&i.SCategoryIdMn,
		&i.PriceMn,
		&i.StockQuantity,
		&i.ImagesPathMn,
		&i.DescriptionMn,
		&i.BrandMn,
		&i.ManufacturedCountryMn,
		&i.ColorId,
		&i.SizeId,
		&i.PenOutputMn,
		&i.FeaturesMn,
		&i.MaterialMn,
		&i.StapleSizeMn,
		&i.CapacityMn,
		&i.WeightMn,
		&i.ThicknessMn,
		&i.PackagingMn,
		&i.UsageMn,
		&i.InstructionsMn,
		&i.ProductCodeMn,
		&i.CostPriceMn,
		&i.RetailPriceMn,
		&i.WarehouseStockMn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getListProductMn = `-- name: GetListProductMn :many
SELECT
    "ProductMnID", "ProductNameMn", "sCategoryIdMn", "PriceMn", "StockQuantity", "ImagesPathMn", "DescriptionMn", "BrandMn", "ManufacturedCountryMn", "ColorId", "SizeId", "PenOutputMn", "FeaturesMn", "MaterialMn", "StapleSizeMn", "CapacityMn", "WeightMn", "ThicknessMn", "PackagingMn", "UsageMn", "InstructionsMn", "ProductCodeMn", "CostPriceMn", "RetailPriceMn", "WarehouseStockMn", "Created_At", "Updated_At"
FROM
    "productMn"
ORDER BY
    "Created_At" DESC
`

func (q *Queries) GetListProductMn(ctx context.Context) ([]ProductMn, error) {
	rows, err := q.db.QueryContext(ctx, getListProductMn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductMn
	for rows.Next() {
		var i ProductMn
		if err := rows.Scan(
			&i.ProductMnID,
			&i.ProductNameMn,
			&i.SCategoryIdMn,
			&i.PriceMn,
			&i.StockQuantity,
			&i.ImagesPathMn,
			&i.DescriptionMn,
			&i.BrandMn,
			&i.ManufacturedCountryMn,
			&i.ColorId,
			&i.SizeId,
			&i.PenOutputMn,
			&i.FeaturesMn,
			&i.MaterialMn,
			&i.StapleSizeMn,
			&i.CapacityMn,
			&i.WeightMn,
			&i.ThicknessMn,
			&i.PackagingMn,
			&i.UsageMn,
			&i.InstructionsMn,
			&i.ProductCodeMn,
			&i.CostPriceMn,
			&i.RetailPriceMn,
			&i.WarehouseStockMn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateByMnImagePath = `-- name: UpdateByMnImagePath :one
UPDATE
    "productMn"
SET
    "ImagesPathMn" = $1
WHERE
    "ProductMnID" = $2 RETURNING "ProductMnID", "ProductNameMn", "sCategoryIdMn", "PriceMn", "StockQuantity", "ImagesPathMn", "DescriptionMn", "BrandMn", "ManufacturedCountryMn", "ColorId", "SizeId", "PenOutputMn", "FeaturesMn", "MaterialMn", "StapleSizeMn", "CapacityMn", "WeightMn", "ThicknessMn", "PackagingMn", "UsageMn", "InstructionsMn", "ProductCodeMn", "CostPriceMn", "RetailPriceMn", "WarehouseStockMn", "Created_At", "Updated_At"
`

type UpdateByMnImagePathParams struct {
	ImagesPathMn string
	ProductMnID  int32
}

func (q *Queries) UpdateByMnImagePath(ctx context.Context, arg UpdateByMnImagePathParams) (ProductMn, error) {
	row := q.db.QueryRowContext(ctx, updateByMnImagePath, arg.ImagesPathMn, arg.ProductMnID)
	var i ProductMn
	err := row.Scan(
		&i.ProductMnID,
		&i.ProductNameMn,
		&i.SCategoryIdMn,
		&i.PriceMn,
		&i.StockQuantity,
		&i.ImagesPathMn,
		&i.DescriptionMn,
		&i.BrandMn,
		&i.ManufacturedCountryMn,
		&i.ColorId,
		&i.SizeId,
		&i.PenOutputMn,
		&i.FeaturesMn,
		&i.MaterialMn,
		&i.StapleSizeMn,
		&i.CapacityMn,
		&i.WeightMn,
		&i.ThicknessMn,
		&i.PackagingMn,
		&i.UsageMn,
		&i.InstructionsMn,
		&i.ProductCodeMn,
		&i.CostPriceMn,
		&i.RetailPriceMn,
		&i.WarehouseStockMn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateByProductMnPrice = `-- name: UpdateByProductMnPrice :one
UPDATE
    "productMn"
SET
    "PriceMn" = $1
WHERE
    "ProductMnID" = $2 RETURNING "ProductMnID", "ProductNameMn", "sCategoryIdMn", "PriceMn", "StockQuantity", "ImagesPathMn", "DescriptionMn", "BrandMn", "ManufacturedCountryMn", "ColorId", "SizeId", "PenOutputMn", "FeaturesMn", "MaterialMn", "StapleSizeMn", "CapacityMn", "WeightMn", "ThicknessMn", "PackagingMn", "UsageMn", "InstructionsMn", "ProductCodeMn", "CostPriceMn", "RetailPriceMn", "WarehouseStockMn", "Created_At", "Updated_At"
`

type UpdateByProductMnPriceParams struct {
	PriceMn     string
	ProductMnID int32
}

func (q *Queries) UpdateByProductMnPrice(ctx context.Context, arg UpdateByProductMnPriceParams) (ProductMn, error) {
	row := q.db.QueryRowContext(ctx, updateByProductMnPrice, arg.PriceMn, arg.ProductMnID)
	var i ProductMn
	err := row.Scan(
		&i.ProductMnID,
		&i.ProductNameMn,
		&i.SCategoryIdMn,
		&i.PriceMn,
		&i.StockQuantity,
		&i.ImagesPathMn,
		&i.DescriptionMn,
		&i.BrandMn,
		&i.ManufacturedCountryMn,
		&i.ColorId,
		&i.SizeId,
		&i.PenOutputMn,
		&i.FeaturesMn,
		&i.MaterialMn,
		&i.StapleSizeMn,
		&i.CapacityMn,
		&i.WeightMn,
		&i.ThicknessMn,
		&i.PackagingMn,
		&i.UsageMn,
		&i.InstructionsMn,
		&i.ProductCodeMn,
		&i.CostPriceMn,
		&i.RetailPriceMn,
		&i.WarehouseStockMn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateByProductMnStockQuantity = `-- name: UpdateByProductMnStockQuantity :one
UPDATE
    "productMn"
SET
    "StockQuantity" = $1
WHERE
    "ProductMnID" = $2 RETURNING "ProductMnID", "ProductNameMn", "sCategoryIdMn", "PriceMn", "StockQuantity", "ImagesPathMn", "DescriptionMn", "BrandMn", "ManufacturedCountryMn", "ColorId", "SizeId", "PenOutputMn", "FeaturesMn", "MaterialMn", "StapleSizeMn", "CapacityMn", "WeightMn", "ThicknessMn", "PackagingMn", "UsageMn", "InstructionsMn", "ProductCodeMn", "CostPriceMn", "RetailPriceMn", "WarehouseStockMn", "Created_At", "Updated_At"
`

type UpdateByProductMnStockQuantityParams struct {
	StockQuantity int32
	ProductMnID   int32
}

func (q *Queries) UpdateByProductMnStockQuantity(ctx context.Context, arg UpdateByProductMnStockQuantityParams) (ProductMn, error) {
	row := q.db.QueryRowContext(ctx, updateByProductMnStockQuantity, arg.StockQuantity, arg.ProductMnID)
	var i ProductMn
	err := row.Scan(
		&i.ProductMnID,
		&i.ProductNameMn,
		&i.SCategoryIdMn,
		&i.PriceMn,
		&i.StockQuantity,
		&i.ImagesPathMn,
		&i.DescriptionMn,
		&i.BrandMn,
		&i.ManufacturedCountryMn,
		&i.ColorId,
		&i.SizeId,
		&i.PenOutputMn,
		&i.FeaturesMn,
		&i.MaterialMn,
		&i.StapleSizeMn,
		&i.CapacityMn,
		&i.WeightMn,
		&i.ThicknessMn,
		&i.PackagingMn,
		&i.UsageMn,
		&i.InstructionsMn,
		&i.ProductCodeMn,
		&i.CostPriceMn,
		&i.RetailPriceMn,
		&i.WarehouseStockMn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProductMn = `-- name: UpdateProductMn :one
UPDATE
    "productMn"
SET
    "ProductNameMn" = $1,
    "sCategoryIdMn" = $2,
    "PriceMn" = $3,
    "StockQuantity" = $4,
    "ImagesPathMn" = $5,
    "DescriptionMn" = $6,
    "BrandMn" = $7,
    "ManufacturedCountryMn" = $8,
    "ColorId" = $9,
    "SizeId" = $10,
    "PenOutputMn" = $11,
    "FeaturesMn" = $12,
    "StapleSizeMn" = $13,
    "CapacityMn" = $14,
    "WeightMn" = $15,
    "ThicknessMn" = $16,
    "PackagingMn" = $17,
    "UsageMn" = $18,
    "InstructionsMn" = $19,
    "ProductCodeMn" = $20,
    "CostPriceMn" = $21,
    "RetailPriceMn" = $22,
    "WarehouseStockMn" = $23
WHERE
    "ProductMnID" = $24 RETURNING "ProductMnID", "ProductNameMn", "sCategoryIdMn", "PriceMn", "StockQuantity", "ImagesPathMn", "DescriptionMn", "BrandMn", "ManufacturedCountryMn", "ColorId", "SizeId", "PenOutputMn", "FeaturesMn", "MaterialMn", "StapleSizeMn", "CapacityMn", "WeightMn", "ThicknessMn", "PackagingMn", "UsageMn", "InstructionsMn", "ProductCodeMn", "CostPriceMn", "RetailPriceMn", "WarehouseStockMn", "Created_At", "Updated_At"
`

type UpdateProductMnParams struct {
	ProductNameMn         string
	SCategoryIdMn         int32
	PriceMn               string
	StockQuantity         int32
	ImagesPathMn          string
	DescriptionMn         string
	BrandMn               string
	ManufacturedCountryMn string
	ColorId               int32
	SizeId                int32
	PenOutputMn           string
	FeaturesMn            string
	StapleSizeMn          string
	CapacityMn            string
	WeightMn              string
	ThicknessMn           string
	PackagingMn           string
	UsageMn               string
	InstructionsMn        string
	ProductCodeMn         string
	CostPriceMn           string
	RetailPriceMn         string
	WarehouseStockMn      int32
	ProductMnID           int32
}

func (q *Queries) UpdateProductMn(ctx context.Context, arg UpdateProductMnParams) (ProductMn, error) {
	row := q.db.QueryRowContext(ctx, updateProductMn,
		arg.ProductNameMn,
		arg.SCategoryIdMn,
		arg.PriceMn,
		arg.StockQuantity,
		arg.ImagesPathMn,
		arg.DescriptionMn,
		arg.BrandMn,
		arg.ManufacturedCountryMn,
		arg.ColorId,
		arg.SizeId,
		arg.PenOutputMn,
		arg.FeaturesMn,
		arg.StapleSizeMn,
		arg.CapacityMn,
		arg.WeightMn,
		arg.ThicknessMn,
		arg.PackagingMn,
		arg.UsageMn,
		arg.InstructionsMn,
		arg.ProductCodeMn,
		arg.CostPriceMn,
		arg.RetailPriceMn,
		arg.WarehouseStockMn,
		arg.ProductMnID,
	)
	var i ProductMn
	err := row.Scan(
		&i.ProductMnID,
		&i.ProductNameMn,
		&i.SCategoryIdMn,
		&i.PriceMn,
		&i.StockQuantity,
		&i.ImagesPathMn,
		&i.DescriptionMn,
		&i.BrandMn,
		&i.ManufacturedCountryMn,
		&i.ColorId,
		&i.SizeId,
		&i.PenOutputMn,
		&i.FeaturesMn,
		&i.MaterialMn,
		&i.StapleSizeMn,
		&i.CapacityMn,
		&i.WeightMn,
		&i.ThicknessMn,
		&i.PackagingMn,
		&i.UsageMn,
		&i.InstructionsMn,
		&i.ProductCodeMn,
		&i.CostPriceMn,
		&i.RetailPriceMn,
		&i.WarehouseStockMn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProductMnSubCategory = `-- name: UpdateProductMnSubCategory :one
UPDATE
    "productMn"
SET
    "sCategoryIdMn" = $1
WHERE
    "ProductMnID" = $2 RETURNING "ProductMnID", "ProductNameMn", "sCategoryIdMn", "PriceMn", "StockQuantity", "ImagesPathMn", "DescriptionMn", "BrandMn", "ManufacturedCountryMn", "ColorId", "SizeId", "PenOutputMn", "FeaturesMn", "MaterialMn", "StapleSizeMn", "CapacityMn", "WeightMn", "ThicknessMn", "PackagingMn", "UsageMn", "InstructionsMn", "ProductCodeMn", "CostPriceMn", "RetailPriceMn", "WarehouseStockMn", "Created_At", "Updated_At"
`

type UpdateProductMnSubCategoryParams struct {
	SCategoryIdMn int32
	ProductMnID   int32
}

func (q *Queries) UpdateProductMnSubCategory(ctx context.Context, arg UpdateProductMnSubCategoryParams) (ProductMn, error) {
	row := q.db.QueryRowContext(ctx, updateProductMnSubCategory, arg.SCategoryIdMn, arg.ProductMnID)
	var i ProductMn
	err := row.Scan(
		&i.ProductMnID,
		&i.ProductNameMn,
		&i.SCategoryIdMn,
		&i.PriceMn,
		&i.StockQuantity,
		&i.ImagesPathMn,
		&i.DescriptionMn,
		&i.BrandMn,
		&i.ManufacturedCountryMn,
		&i.ColorId,
		&i.SizeId,
		&i.PenOutputMn,
		&i.FeaturesMn,
		&i.MaterialMn,
		&i.StapleSizeMn,
		&i.CapacityMn,
		&i.WeightMn,
		&i.ThicknessMn,
		&i.PackagingMn,
		&i.UsageMn,
		&i.InstructionsMn,
		&i.ProductCodeMn,
		&i.CostPriceMn,
		&i.RetailPriceMn,
		&i.WarehouseStockMn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSProductMn = `-- name: UpdateSProductMn :one
UPDATE
    "productMn"
SET
    "StockQuantity" = $1
WHERE
    "ProductMnID" = $2 RETURNING "ProductMnID", "ProductNameMn", "sCategoryIdMn", "PriceMn", "StockQuantity", "ImagesPathMn", "DescriptionMn", "BrandMn", "ManufacturedCountryMn", "ColorId", "SizeId", "PenOutputMn", "FeaturesMn", "MaterialMn", "StapleSizeMn", "CapacityMn", "WeightMn", "ThicknessMn", "PackagingMn", "UsageMn", "InstructionsMn", "ProductCodeMn", "CostPriceMn", "RetailPriceMn", "WarehouseStockMn", "Created_At", "Updated_At"
`

type UpdateSProductMnParams struct {
	StockQuantity int32
	ProductMnID   int32
}

func (q *Queries) UpdateSProductMn(ctx context.Context, arg UpdateSProductMnParams) (ProductMn, error) {
	row := q.db.QueryRowContext(ctx, updateSProductMn, arg.StockQuantity, arg.ProductMnID)
	var i ProductMn
	err := row.Scan(
		&i.ProductMnID,
		&i.ProductNameMn,
		&i.SCategoryIdMn,
		&i.PriceMn,
		&i.StockQuantity,
		&i.ImagesPathMn,
		&i.DescriptionMn,
		&i.BrandMn,
		&i.ManufacturedCountryMn,
		&i.ColorId,
		&i.SizeId,
		&i.PenOutputMn,
		&i.FeaturesMn,
		&i.MaterialMn,
		&i.StapleSizeMn,
		&i.CapacityMn,
		&i.WeightMn,
		&i.ThicknessMn,
		&i.PackagingMn,
		&i.UsageMn,
		&i.InstructionsMn,
		&i.ProductCodeMn,
		&i.CostPriceMn,
		&i.RetailPriceMn,
		&i.WarehouseStockMn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
