// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: producten_color.sql

package db

import (
	"context"
)

const insertProductEnColor = `-- name: InsertProductEnColor :one
INSERT INTO "productEn_colors" ("ProductEnID", "ColorId")
VALUES (
    $1, 
   $2 
) RETURNING "ProductEnID", "ColorId"
`

type InsertProductEnColorParams struct {
	ProductEnID int32
	ColorId     int32
}

func (q *Queries) InsertProductEnColor(ctx context.Context, arg InsertProductEnColorParams) (ProductEnColor, error) {
	row := q.db.QueryRowContext(ctx, insertProductEnColor, arg.ProductEnID, arg.ColorId)
	var i ProductEnColor
	err := row.Scan(&i.ProductEnID, &i.ColorId)
	return i, err
}
