// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: productmn_sizes.sql

package db

import (
	"context"
)

const insertProductMnSize = `-- name: InsertProductMnSize :one
INSERT into "productMn_sizes" ("ProductMnID", "SizeId") VALUES (
    $1,
    $2
) RETURNING "ProductMnID", "SizeId"
`

type InsertProductMnSizeParams struct {
	ProductMnID int32
	SizeId      int32
}

func (q *Queries) InsertProductMnSize(ctx context.Context, arg InsertProductMnSizeParams) (ProductMnSize, error) {
	row := q.db.QueryRowContext(ctx, insertProductMnSize, arg.ProductMnID, arg.SizeId)
	var i ProductMnSize
	err := row.Scan(&i.ProductMnID, &i.SizeId)
	return i, err
}
