// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: productmn_colors.sql

package db

import (
	"context"
)

const insertProductMnColor = `-- name: InsertProductMnColor :one
INSERT into "productMn_colors" ("ProductMnID", "ColorId") VALUES (
    $1,
    $2
) RETURNING "ProductMnID", "ColorId"
`

type InsertProductMnColorParams struct {
	ProductMnID int32
	ColorId     int32
}

func (q *Queries) InsertProductMnColor(ctx context.Context, arg InsertProductMnColorParams) (ProductMnColor, error) {
	row := q.db.QueryRowContext(ctx, insertProductMnColor, arg.ProductMnID, arg.ColorId)
	var i ProductMnColor
	err := row.Scan(&i.ProductMnID, &i.ColorId)
	return i, err
}
