// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: sCategoryMn.sql

package db

import (
	"context"
)

const createSCategoryMn = `-- name: CreateSCategoryMn :one
INSERT INTO
    "sCategoryMn" (
        "sCategoryNameMn",
        "SubCategoryIDMn"
    )
VALUES
    (
        $1,
        $2
    ) RETURNING "sCategoryIdMn", "sCategoryNameMn", "SubCategoryIDMn"
`

type CreateSCategoryMnParams struct {
	SCategoryNameMn string
	SubCategoryIDMn int32
}

func (q *Queries) CreateSCategoryMn(ctx context.Context, arg CreateSCategoryMnParams) (SCategoryMn, error) {
	row := q.db.QueryRowContext(ctx, createSCategoryMn, arg.SCategoryNameMn, arg.SubCategoryIDMn)
	var i SCategoryMn
	err := row.Scan(&i.SCategoryIdMn, &i.SCategoryNameMn, &i.SubCategoryIDMn)
	return i, err
}

const deleteSCategoryMn = `-- name: DeleteSCategoryMn :exec
DELETE FROM
    "sCategoryMn"
WHERE
    "sCategoryIdMn" = $1
`

func (q *Queries) DeleteSCategoryMn(ctx context.Context, scategoryidmn int32) error {
	_, err := q.db.ExecContext(ctx, deleteSCategoryMn, scategoryidmn)
	return err
}

const findBySCategoryIdMn = `-- name: FindBySCategoryIdMn :one
SELECT
    "sCategoryIdMn", "sCategoryNameMn", "SubCategoryIDMn"
FROM
    "sCategoryMn"
WHERE
    "sCategoryIdMn" = $1
LIMIT 1
`

func (q *Queries) FindBySCategoryIdMn(ctx context.Context, scategoryidmn int32) (SCategoryMn, error) {
	row := q.db.QueryRowContext(ctx, findBySCategoryIdMn, scategoryidmn)
	var i SCategoryMn
	err := row.Scan(&i.SCategoryIdMn, &i.SCategoryNameMn, &i.SubCategoryIDMn)
	return i, err
}

const findBySCategoryNameMn = `-- name: FindBySCategoryNameMn :one
SELECT  
    "sCategoryIdMn", "sCategoryNameMn", "SubCategoryIDMn"
FROM
    "sCategoryMn"
WHERE
    "sCategoryNameMn" = $1
LIMIT
 1
`

func (q *Queries) FindBySCategoryNameMn(ctx context.Context, scategorynamemn string) (SCategoryMn, error) {
	row := q.db.QueryRowContext(ctx, findBySCategoryNameMn, scategorynamemn)
	var i SCategoryMn
	err := row.Scan(&i.SCategoryIdMn, &i.SCategoryNameMn, &i.SubCategoryIDMn)
	return i, err
}

const getAllSCategoriesMn = `-- name: GetAllSCategoriesMn :many
SELECT
    "sCategoryIdMn", "sCategoryNameMn", "SubCategoryIDMn"
FROM
    "sCategoryMn"
`

func (q *Queries) GetAllSCategoriesMn(ctx context.Context) ([]SCategoryMn, error) {
	rows, err := q.db.QueryContext(ctx, getAllSCategoriesMn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SCategoryMn
	for rows.Next() {
		var i SCategoryMn
		if err := rows.Scan(&i.SCategoryIdMn, &i.SCategoryNameMn, &i.SubCategoryIDMn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductBySCategoriesMn = `-- name: GetProductBySCategoriesMn :many
SELECT
    p."ProductMnID",
    p."ProductNameMn",
    p."PriceMn",
    p."StockQuantity",
    p."ImagesPathMn"
FROM
    "sCategoryMn" sc
    JOIN "productMn" p ON sc."sCategoryIdMn" = p."sCategoryIdMn"
WHERE
    sc."sCategoryIdMn" = $1
`

type GetProductBySCategoriesMnRow struct {
	ProductMnID   int32
	ProductNameMn string
	PriceMn       string
	StockQuantity int32
	ImagesPathMn  string
}

func (q *Queries) GetProductBySCategoriesMn(ctx context.Context, scategoryidmn int32) ([]GetProductBySCategoriesMnRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductBySCategoriesMn, scategoryidmn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductBySCategoriesMnRow
	for rows.Next() {
		var i GetProductBySCategoriesMnRow
		if err := rows.Scan(
			&i.ProductMnID,
			&i.ProductNameMn,
			&i.PriceMn,
			&i.StockQuantity,
			&i.ImagesPathMn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSCategoryByIdMn = `-- name: UpdateSCategoryByIdMn :exec
UPDATE  
    "sCategoryMn"
SET
    "sCategoryNameMn" = $1,
    "SubCategoryIDMn" = $2
WHERE
    "sCategoryIdMn" = $3 RETURNING "sCategoryIdMn", "sCategoryNameMn", "SubCategoryIDMn"
`

type UpdateSCategoryByIdMnParams struct {
	SCategoryNameMn string
	SubCategoryIDMn int32
	SCategoryIdMn   int32
}

func (q *Queries) UpdateSCategoryByIdMn(ctx context.Context, arg UpdateSCategoryByIdMnParams) error {
	_, err := q.db.ExecContext(ctx, updateSCategoryByIdMn, arg.SCategoryNameMn, arg.SubCategoryIDMn, arg.SCategoryIdMn)
	return err
}

const updateSCategoryNameMn = `-- name: UpdateSCategoryNameMn :one
UPDATE "sCategoryMn"
SET "sCategoryNameMn" = $1
WHERE "sCategoryIdMn" = $2 RETURNING "sCategoryIdMn", "sCategoryNameMn", "SubCategoryIDMn"
`

type UpdateSCategoryNameMnParams struct {
	SCategoryNameMn string
	SCategoryIdMn   int32
}

func (q *Queries) UpdateSCategoryNameMn(ctx context.Context, arg UpdateSCategoryNameMnParams) (SCategoryMn, error) {
	row := q.db.QueryRowContext(ctx, updateSCategoryNameMn, arg.SCategoryNameMn, arg.SCategoryIdMn)
	var i SCategoryMn
	err := row.Scan(&i.SCategoryIdMn, &i.SCategoryNameMn, &i.SubCategoryIDMn)
	return i, err
}
