name: Deploy Go App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up SSH
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Step 3: Deploy to the server
    - name: Deploy Go App
      run: |
        ssh -o StrictHostKeyChecking=no cloudmn@103.50.205.86 << 'EOF'
          sudo systemctl stop my-go-app.service || true

          cd ~/UserBackendService/
          git pull origin main

          go build -o main main.go
          sudo systemctl start my-go-app.service

          sudo systemctl reload nginx
        EOF
